- name: Exec emcgrab.sh
  shell: "./emcgrab.sh -autoexec -legal"
  
- name: Fetch result .tar to ansible
  fetch: 
    src: /opt/emcgrab/outputs/*
    dest: /tmp/outputs/
    
- name: Delete last output
  file:
    src: /opt/emcgrab/outputs/*
    state: absent
