- name: Copy file to remote host
  copy: 
    src: /tmp/emcgrab*
    dest: /opt/emcgrab/
  when: ""{{ inventory_hostname == 'uxbck016' }}"
  
- name: Untar emcgrab
  unarchive:
    src: /opt/emcgrab*.tar
    dest: /opt/emcgrab
